version: '3.8'
services:
  impostor:
    image: aeonlucid/impostor:v1.8.4
    # image: aoirint/impostor:v20221223.1
    restart: always
    ports:
      - "${HOST_GAME_PORT:?}:22023/udp"
    volumes:
      - "./config/config.json:/app/config.json"
      - "./config/config_http.json:/app/config_http.json"
      - "./plugins:/app/plugins"
      - "./libraries:/app/libraries"

  nginx:
    image: nginx:latest
    restart: always
    depends_on:
      - impostor
    volumes:
      - ./nginx_templates:/etc/nginx/templates
      - ${NGINX_LOG_DIR:?}:/logs
    environment:
      - NGINX_ENVSUBST_TEMPLATE_SUFFIX=.nginx

  cloudflared:
    image: cloudflare/cloudflared:latest
    command: tunnel run
    restart: always
    depends_on:
      - nginx
    environment:
      TUNNEL_TOKEN: ${CLOUDFLARED_TUNNEL_TOKEN:?}
