version: '3.8'
services:
  impostor:
    # image: aeonlucid/impostor:v1.7.1
    # image: aoirint/impostor:v20230106.1
    image: aoirint/impostor:v20230106.5-aspnet
    ports:
      - "${HOST_PORT}:22023/udp"
      - "${HOST_HTTP_PORT}:22000/tcp"
    volumes:
      - "./config/config.json:/app/config.json"
      - "./config/config_http.json:/app/config_http.json"
      - "./plugins:/app/plugins"
      - "./libraries:/app/libraries"

