version: '3.8'
services:
  impostor:
    # image: aeonlucid/impostor:v1.7.1
    image: aoirint/impostor:v20220824.2
    ports:
      - "${HOST_PORT}:22023/udp"
    volumes:
      - "./config/config.json:/app/config.json"
      - "./plugins:/app/plugins"
      - "./libraries:/app/libraries"

